version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: outleads-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: outleads_dev
      POSTGRES_USER: outleads_user
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - outleads-dev-network

  # Redis Cache for Development
  redis:
    image: redis:7-alpine
    container_name: outleads-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - outleads-dev-network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  outleads-dev-network:
    driver: bridge
